CREATE DATABASE ClassDB;

USE ClassDB;


CREATE TABLE students (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    present BOOLEAN
);


INSERT INTO students (id, name, present) VALUES
(1, 'fatima ezzahra tousse', FALSE),
(2, 'fatima zahra ouchen', FALSE),
(3, 'khaoula bekarri', FALSE),
(4, 'aya el abdllaoui', FALSE),
(5, 'ferdaous assaadi', FALSE),
(6, 'hamza hadraf', FALSE),
(7, 'charifa fax', FALSE),
(8, 'mouad erraji', FALSE),
(9, 'oualid lahbal', FALSE),
(10, 'othmane elbarnaty', FALSE),
(11, 'adam el marnissi', FALSE),
(12, 'jihane karimidrissi', FALSE),
(13, 'hicham chaabi', FALSE),
(14, 'laila elaasri', FALSE),
(15, 'ilham aghad', FALSE),
(16, 'zineb echchayeb', FALSE),
(17, 'achrine asma', FALSE),
(18, 'el mahdi iskander', FALSE),
(19, 'donia karroum', FALSE),
(20, 'tariq tghmmaoui', FALSE),
(21, 'idriss rhounimi', FALSE),
(22, 'basma oudra', FALSE),
(23, 'malak sousane', FALSE),
(24, 'hasnaa abidar', FALSE),
(25, 'achraf houdif', FALSE),
(26, 'ayman-ziad taaimira', FALSE),
(27, 'oussama adribina', FALSE),
(28, 'rania aattar', FALSE),
(29, 'mohamed achtout', FALSE),
(30, 'oumaima bazoui', FALSE),
(31, 'aya bajad', FALSE),
(32, 'hiba fatihi', FALSE),
(33, 'marwa atir', FALSE),
(34, 'rachid aarag', FALSE),
(35, 'khalid abaid', FALSE),
(36, 'meriem abbahoum', FALSE),
(37, 'mohamed achtout', FALSE),
(38, 'hamza ait bouhou', FALSE),
(39, 'asma ajarour', FALSE),
(40, 'nour elhouda', FALSE),
(41, 'hajar baba', FALSE),
(42, 'amira bahanni', FALSE),
(43, 'mahmoud benhammou', FALSE),
(44, 'insaf benimethar', FALSE),
(45, 'oumaima bentoumi', FALSE),
(46, 'ayoub bouaoud', FALSE),
(47, 'salma bouya hadda', FALSE),
(48, 'ayman bouzroud', FALSE),
(49, 'saad chabili', FALSE),
(50, 'marouane el arbaoui', FALSE),
(51, 'rami el arbaoui', FALSE),
(52, 'youssef el fassih', FALSE),
(53, 'nisrine el mahdani', FALSE),
(54, 'yahia el mhadder', FALSE),
(55, 'elmahdi el mhadri', FALSE),
(56, 'jamila el-abid', FALSE),
(57, 'ikram elhoudaili', FALSE),
(58, 'yahya elmjiyed', FALSE),
(59, 'imane ennaji', FALSE),
(60, 'abdelouahab ettezguini', FALSE),
(61, 'khadija idhamou', FALSE),
(62, 'lahcen igrouchfi', FALSE),
(63, 'doha isianioui', FALSE),
(64, 'farah kamboua', FALSE),
(65, 'donia karroum', FALSE),
(66, 'chaima kezibri', FALSE),
(67, 'abdelmajid kila', FALSE),
(68, 'anass korsan', FALSE),
(69, 'asmae laaliany', FALSE),
(70, 'yassine malal', FALSE),
(71, 'hatim marouach', FALSE),
(72, 'lina monybe', FALSE),
(73, 'hajar mounji', FALSE),
(74, 'basma oudra', FALSE),
(75, 'idriss rhounimi', FALSE),
(76, 'hiba sarhane', FALSE),
(77, 'ilyas thaimi', FALSE),
(78, 'ilyass zaid', FALSE);